# Generated by Django 4.2.13 on 2024-10-16 00:57

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user_type",
                    models.CharField(
                        choices=[(1, "HOD"), (2, "Staff"), (3, "Student")],
                        default=1,
                        max_length=10,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AnneeScolaire",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("session_start_year", models.DateField()),
                ("session_end_year", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("attendance_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Chapitres",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titre_chapitres", models.CharField(max_length=100)),
                ("numero_chapitres", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Classess",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom_classes", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Courses",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("course_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cycles",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom_cycles", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Disciplines",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom_disciplines", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Lecons",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_heures", models.PositiveIntegerField(default=1)),
                ("detail_lecons", models.CharField(max_length=200)),
                (
                    "chapitres_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.chapitres",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Semaines",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("numero_semaines", models.PositiveIntegerField(default=1)),
                ("debut_semaines", models.DateField()),
                ("fin_semaines", models.DateField()),
                (
                    "annee_scolaire_id",
                    models.ForeignKey(
                        default=2,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.anneescolaire",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SessionYearModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("session_start_year", models.DateField()),
                ("session_end_year", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Subjects",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("subject_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.courses",
                    ),
                ),
                (
                    "staff_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("gender", models.CharField(max_length=50)),
                ("profile_pic", models.FileField(upload_to="")),
                ("address", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="student_management_app.courses",
                    ),
                ),
                (
                    "session_year_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.sessionyearmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentResult",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("subject_exam_marks", models.FloatField(default=0)),
                ("subject_assignment_marks", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.students",
                    ),
                ),
                (
                    "subject_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.subjects",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staffs",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("address", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "annee_scolaire_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.anneescolaire",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SemainesLeconsReelle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("lecon_duree_reelle", models.PositiveIntegerField(default=0)),
                (
                    "lecons_id_relle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.lecons",
                    ),
                ),
                (
                    "semaines_id_Relle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.semaines",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SemainesLecons",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1", "En attente"),
                            ("2", "En cours"),
                            ("3", "Terminer"),
                        ],
                        default=1,
                        max_length=2,
                    ),
                ),
                (
                    "lecons_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.lecons",
                    ),
                ),
                (
                    "semaines_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.semaines",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationStudent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.students",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationStaffs",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stafff_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.staffs",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Niveaux",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom_niveaux", models.CharField(max_length=255)),
                (
                    "cycles_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.cycles",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Matieres",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "classes_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.classess",
                    ),
                ),
                (
                    "nom_matieres",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.disciplines",
                    ),
                ),
                (
                    "professeurs_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.staffs",
                    ),
                ),
            ],
            options={
                "unique_together": {("nom_matieres", "classes_id", "professeurs_id")},
            },
        ),
        migrations.AddField(
            model_name="lecons",
            name="semaines",
            field=models.ManyToManyField(
                through="student_management_app.SemainesLecons",
                to="student_management_app.semaines",
            ),
        ),
        migrations.CreateModel(
            name="LeaveReportStudent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("leave_date", models.CharField(max_length=255)),
                ("leave_message", models.TextField()),
                ("leave_status", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.students",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeaveReportStaff",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("leave_date", models.CharField(max_length=255)),
                ("leave_message", models.TextField()),
                ("leave_status", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.staffs",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedBackStudent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("feedback", models.TextField()),
                ("feedback_reply", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.students",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedBackStaffs",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("feedback", models.TextField()),
                ("feedback_reply", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.staffs",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="classess",
            name="niveaux_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="student_management_app.niveaux",
            ),
        ),
        migrations.AddField(
            model_name="chapitres",
            name="matieres_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="student_management_app.matieres",
            ),
        ),
        migrations.CreateModel(
            name="AttendanceReport",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendance_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.attendance",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="student_management_app.students",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="attendance",
            name="session_year_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="student_management_app.sessionyearmodel",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="subject_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="student_management_app.subjects",
            ),
        ),
        migrations.CreateModel(
            name="AdminHOD",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
