# Generated by Django 4.2.13 on 2024-10-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0002_uploadedfile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadedFile",
        ),
    ]
