# Generated by Django 4.2.13 on 2024-09-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0002_alter_customuser_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
