# Generated by Django 4.2.13 on 2024-09-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0003_alter_author_id_alter_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
