# Generated by Django 4.2.13 on 2024-09-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0004_alter_customuser_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Book",
        ),
    ]
